import { Link } from "react-router-dom";

export default function TermsAndConditions ()  {
    return (
        <section className="termsAndConditions">
            <div className="container bg-white text-start">
                <div className="container p-4 text-start pt-5">
                    <h1 className="">Terms and Conditions</h1>
                    <p className="text">Our Terms and Conditions of Service were last updated on: 8th April 2025. Please ensure that you have read and reviewed these Terms and Conditions in conjunction with our Privacy Policy (<Link to="/privacypolicy"><strong>here</strong></Link>).</p>
                    <p className="text">If you have any questions or queries in relation to our Terms and Conditions or our Privacy Policy, please do not hesitate to contact us by using the contact details below.</p>
                    <p className="index">In these Terms and Conditions, unless otherwise specified, the use of the words ‘us’, ‘we’, or ‘our’ refers to Milestone Accounting Pty Ltd (ACN 000 000 000) trading as The same day tax refund (including any of our agents). We are a Registered Tax Agent (Registration No. 00000000) which owns, operates and controls the website (inclusive of all electronic or online facilities and any underlying software and platform through which you may access and use our services) accessible at <Link to="/">https://www.samedaytaxrefund.com.au/</Link> (“<strong>Website</strong>”). We provide “<strong>Tax Agent Services</strong>”, being any service that relates to ascertaining your liabilities, obligations or entitlements under applicable taxation laws of Australia. Tax Agent Services includes but is not limited to services such as preparing returns, notices, statements, applications or other documents regarding your liabilities, obligations or entitlements under an applicable taxation law. Any use of the word ‘you’ or ‘your’ refers to you as a user, being an individual or entity accessing or using our Website.</p>
                    <ol>
                        <li className="index_item">Our Terms and Conditions, in conjunction with our Privacy Policy form the terms governing the use of our Website and the agreement that operates between you and us when accessing and using our Website.</li>
                        <li className="index_item">Our Terms and Conditions set out the rights and obligations of each party in respect of access and use of our Website.</li>
                    </ol>
                    <h2 className="index_item"><b>Acceptance</b></h2>
                    <ol>
                        <li className="index_item">Your use and access to our Website is conditional upon acceptance of and compliance with these Terms and Conditions.</li>
                        <li className="index_item">By accessing and using our Website, you acknowledge that you have read and accept our Terms and Conditions and Privacy Policy, and agree to be legally bound by these Terms and Conditions.</li>
                        <li className="index_item">If you disagree with any part of our Terms and Conditions, you must immediately cease the use of our Website.</li>
                        <li className="index_item">From time to time, we may change our Terms and Conditions. We solely have the right to amend our Terms and Conditions at any time. The use of our Website by you will be deemed to be acceptance of our Terms and Conditions as amended from time to time. You must ensure that in accessing our Website, you review our Terms and Conditions as updated and amended from time to time. You may request amendments or changes for our consideration.</li>
                        <li className="index_item">If any provision of these Terms and Conditions is deemed to be void, invalid, vitiated, or unenforceable to any extent, such provision shall be enforced to the greatest extent permitted by law, and the remainder of these Terms and Conditions shall continue to operate and shall be binding upon you.</li>
                    </ol>
                    <h2 className="index_item"><b>Jurisdiction &amp; Governing Law</b></h2>
                    <ol>
                        <li className="index_item">Your use of our Website, our Terms and Conditions and Privacy Policy are governed by and construed in accordance with the laws of the State of New South Wales, Australia, and are subject to the laws of the Commonwealth of Australia wherever so applicable.</li>
                        <li className="index_item">The courts of the State of New South Wales (and the Commonwealth of Australia wherever applicable) shall have jurisdiction in respect of, or arising from or in connection to our Website, these Terms and Conditions, and the Privacy Policy.</li>
                        <li className="index_item">If there is any dispute between us and you which cannot be resolved within 7 days (or within such further period as the parties agree upon), the parties to the dispute must seek to agree on a process for resolving whole or part of the dispute through means other than litigation and by way of alternative dispute resolution including further negotiations, mediation, conciliation, or independent expert determination, and the procedure and timetable for any process relating to the resolution of the relevant dispute.</li>
                        <li className="index_item">Following the expiration of the agreed timetable or failure to resolve the dispute by way of alternative dispute resolution, either party may commence litigation. If a party fails to engage or participate in good faith under the alternative dispute resolution clause above, the other party may commence litigation.</li>
                    </ol>
                    <h2 className="index_item">General Terms of Use of our Website</h2>
                    <ol>
                        <li className="index_item">You understand and agree that your access and use of our Website is at your own discretion and risk.</li>
                        <li className="index_item">Any content, information, material or recommendations on our Website are not intended for the purposes of providing comprehensive information or providing taxation, financial, business, superannuation or other professional advice to you. Any reliance placed on the information, material, content and recommendations contained on our Website is at your own discretion and therefore risk. We do not know your specific personal circumstances and therefore cannot provide advice or services when you engage us.</li>
                        <li className="index_item">You understand and agree that your access and/or use of our Website is provided by us in good faith on an “as is” and “as available” basis. We shall endeavour to take reasonable steps to keep our Website (and its content, information and material) as secure, up to date, reliable, current, complete, and accurate. We may from time to time, without notice to you, amend, delete, or insert information, content or material on our Website.</li>
                        <li className="index_item">We do not make any warranties or representations including, but not limited to the security, confidentiality, accuracy, reliability, or completeness of the material or information contained on our Website.</li>
                        <li className="index_item">We shall not be held responsible or liable in the event that any information or material on our Website is deemed to be inaccurate, incorrect, incomplete, unreliable, unsecure, and/or out of date.</li>
                        <li className="index_item">From time to time, you may experience interruptions without notice to the access and use of our Website due to (including but not limited to) periodic updates, maintenance or repair, system or network failures, software or hardware malfunctions, or emergencies or unforeseen events (such as natural disasters). In such circumstances, we will not be responsible to you if, for any reason, our Website is not available to you at any such time.</li>
                        <li className="index_item">You acknowledge and agree that we will not be held liable or responsible if any interference, damage or loss occurs in connection with access and use of our Website and any linked third-party websites or pages. You are solely responsible for taking all precautions and measures necessary in accessing and/or using our Website and any linked third-party websites or pages (including but not limited to security measures such as anti-virus or anti-spam software).</li>
                        <li className="index_item">Our Website may contain links to other pages or websites owned and operated by unrelated third parties, and may on occasion display information, content, and resources provided by that third party within the frames of our Website. Such links are provided for the purposes of convenience only and may not be current.</li>
                        <li className="index_item">We shall not be held responsible for any third-party links or the content of those third-party pages or websites. We do not warrant or represent that those links and/or the content of those third-party websites will be free from error or mistake, complete or current, uninterrupted, secure or confidential. You solely bear the risk if you access links to third-party websites as contained on our Website.</li>
                        <li className="index_item">We do not endorse the content of such third-party pages or websites. We have no control over the operation or content of such websites or pages. We disclaim any liability or responsibility for any loss or damage you suffer or incur as a result of accessing or using any third-party websites or its content, or from any reliance placed on such third-party websites or pages. You also acknowledge and agree that we are not liable to you for any loss or damage you may suffer from your own access or use of third-party websites or pages.</li>
                    </ol>
                </div>
            </div>
        </section>
    );
}

