import { Link } from "react-router-dom";

export default function TermsAndConditions ()  {
    return (
        <section className="termsAndConditions">
            <div className="container bg-white text-start">
                <div className="container p-4 text-start pt-5">
                    <h1 className=""><b>Terms and Conditions</b></h1>
                    <p className="text">Our Terms and Conditions of Service were last updated on: 8th April 2025. Please ensure that you have read and reviewed these Terms and Conditions in conjunction with our Privacy Policy (<Link to="/privacypolicy"><strong>here</strong></Link>).</p>
                    <p className="text">If you have any questions or queries in relation to our Terms and Conditions or our Privacy Policy, please do not hesitate to contact us by using the contact details below.</p>
                    <p className="">In these Terms and Conditions, unless otherwise specified, the use of the words ‘us’, ‘we’, or ‘our’ refers to Milestone Accounting Pty Ltd (ACN 000 000 000) trading as The same day tax refund (including any of our agents). We are a Registered Tax Agent (Registration No. 00000000) which owns, operates and controls the website (inclusive of all electronic or online facilities and any underlying software and platform through which you may access and use our services) accessible at <Link to="/">https://www.samedaytaxrefund.com.au/</Link> (“<strong>Website</strong>”). We provide “<strong>Tax Agent Services</strong>”, being any service that relates to ascertaining your liabilities, obligations or entitlements under applicable taxation laws of Australia. Tax Agent Services includes but is not limited to services such as preparing returns, notices, statements, applications or other documents regarding your liabilities, obligations or entitlements under an applicable taxation law. Any use of the word ‘you’ or ‘your’ refers to you as a user, being an individual or entity accessing or using our Website.</p>
                    <h2 className="num-lvl-1"><b>Acknowledgment&nbsp;</b></h2>
                    <ol className="index">
                        <li className="index_item">Our Terms and Conditions, in conjunction with our Privacy Policy form the terms governing the use of our Website and the agreement that operates between you and us when accessing and using our Website.</li>
                        <li className="index_item">Our Terms and Conditions set out the rights and obligations of each party in respect of access and use of our Website.</li>
                    </ol>
                    <h2 className="num-lvl-1"><b>Acceptance</b></h2>
                    <ol className="index">
                        <li className="index_item">Your use and access to our Website is conditional upon acceptance of and compliance with these Terms and Conditions.</li>
                        <li className="index_item">By accessing and using our Website, you acknowledge that you have read and accept our Terms and Conditions and Privacy Policy, and agree to be legally bound by these Terms and Conditions.</li>
                        <li className="index_item">If you disagree with any part of our Terms and Conditions, you must immediately cease the use of our Website.</li>
                        <li className="index_item">From time to time, we may change our Terms and Conditions. We solely have the right to amend our Terms and Conditions at any time. The use of our Website by you will be deemed to be acceptance of our Terms and Conditions as amended from time to time. You must ensure that in accessing our Website, you review our Terms and Conditions as updated and amended from time to time. You may request amendments or changes for our consideration.</li>
                        <li className="index_item">If any provision of these Terms and Conditions is deemed to be void, invalid, vitiated, or unenforceable to any extent, such provision shall be enforced to the greatest extent permitted by law, and the remainder of these Terms and Conditions shall continue to operate and shall be binding upon you.</li>
                    </ol>
                    <h2 className="num-lvl-1"><b>Jurisdiction &amp; Governing Law</b></h2>
                    <ol className="index">
                        <li  className="index_item">Your use of our Website, our Terms and Conditions and Privacy Policy are governed by and construed in accordance with the laws of the State of New South Wales, Australia, and are subject to the laws of the Commonwealth of Australia wherever so applicable.</li>
                        <li className="index_item">The courts of the State of New South Wales (and the Commonwealth of Australia wherever applicable) shall have jurisdiction in respect of, or arising from or in connection to our Website, these Terms and Conditions, and the Privacy Policy.</li>
                        <li className="index_item">If there is any dispute between us and you which cannot be resolved within 7 days (or within such further period as the parties agree upon), the parties to the dispute must seek to agree on a process for resolving whole or part of the dispute through means other than litigation and by way of alternative dispute resolution including further negotiations, mediation, conciliation, or independent expert determination, and the procedure and timetable for any process relating to the resolution of the relevant dispute.</li>
                        <li className="index_item">Following the expiration of the agreed timetable or failure to resolve the dispute by way of alternative dispute resolution, either party may commence litigation. If a party fails to engage or participate in good faith under the alternative dispute resolution clause above, the other party may commence litigation.</li>
                    </ol>
                    <h2 className="num-lvl-1"><b>General Terms of Use of our Website</b></h2>
                    <ol className="index">
                        <li className="index_item">You understand and agree that your access and use of our Website is at your own discretion and risk.</li>
                        <li className="index_item">Any content, information, material or recommendations on our Website are not intended for the purposes of providing comprehensive information or providing taxation, financial, business, superannuation or other professional advice to you. Any reliance placed on the information, material, content and recommendations contained on our Website is at your own discretion and therefore risk. We do not know your specific personal circumstances and therefore cannot provide advice or services when you engage us.</li>
                        <li className="index_item">You understand and agree that your access and/or use of our Website is provided by us in good faith on an “as is” and “as available” basis. We shall endeavour to take reasonable steps to keep our Website (and its content, information and material) as secure, up to date, reliable, current, complete, and accurate. We may from time to time, without notice to you, amend, delete, or insert information, content or material on our Website.</li>
                        <li className="index_item">We do not make any warranties or representations including, but not limited to the security, confidentiality, accuracy, reliability, or completeness of the material or information contained on our Website.</li>
                        <li className="index_item">We shall not be held responsible or liable in the event that any information or material on our Website is deemed to be inaccurate, incorrect, incomplete, unreliable, unsecure, and/or out of date.</li>
                        <li className="index_item">From time to time, you may experience interruptions without notice to the access and use of our Website due to (including but not limited to) periodic updates, maintenance or repair, system or network failures, software or hardware malfunctions, or emergencies or unforeseen events (such as natural disasters). In such circumstances, we will not be responsible to you if, for any reason, our Website is not available to you at any such time.</li>
                        <li className="index_item">You acknowledge and agree that we will not be held liable or responsible if any interference, damage or loss occurs in connection with access and use of our Website and any linked third-party websites or pages. You are solely responsible for taking all precautions and measures necessary in accessing and/or using our Website and any linked third-party websites or pages (including but not limited to security measures such as anti-virus or anti-spam software).</li>
                        <li className="index_item">Our Website may contain links to other pages or websites owned and operated by unrelated third parties, and may on occasion display information, content, and resources provided by that third party within the frames of our Website. Such links are provided for the purposes of convenience only and may not be current.</li>
                        <li className="index_item">We shall not be held responsible for any third-party links or the content of those third-party pages or websites. We do not warrant or represent that those links and/or the content of those third-party websites will be free from error or mistake, complete or current, uninterrupted, secure or confidential. You solely bear the risk if you access links to third-party websites as contained on our Website.</li>
                        <li className="index_item">We do not endorse the content of such third-party pages or websites. We have no control over the operation or content of such websites or pages. We disclaim any liability or responsibility for any loss or damage you suffer or incur as a result of accessing or using any third-party websites or its content, or from any reliance placed on such third-party websites or pages. You also acknowledge and agree that we are not liable to you for any loss or damage you may suffer from your own access or use of third-party websites or pages.</li>
                    </ol>
                    <h2 className="num-lvl-1"><b>Content&nbsp;</b></h2>
                    <ol className="index">
                        <li className="index_item">Other than third party information and links to third-party webpages and websites, we either own or licence from third parties, all rights, title and interest (including, but not limited to copyright, designs, patents, and trademarks) on our Website and in respect of all information, content and material contained on our Website (including but not limited to all text, graphics, images and photos, logos, audio, and software).</li>
                        <li className="index_item">You acknowledge and agree that your access and/or use of our Website does not grant or transfer any rights, title, entitlements or interest to you including without limitation intellectual property rights.</li>
                        <li className="index_item">You acknowledge by using our Website, you agree and hereby grant an irrevocable, perpetual, and royalty-free licence to us to use any of your comments and/or feedback provided to us by you through the use of our Website, and may be used by us for commercial and non-commercial purposes.</li>
                        <li className="index_item">You acknowledge that any modification, copying, transmission, reproduction, publication or redistribution of any information, content or material contained on our Website is strictly prohibited, and may result in the enforcement of civil and/or criminal action or penalties. We reserve the right to seek damages as permitted under any applicable laws, regulations, and codes.</li>
                        <li className="index_item">You must not engage in activities, including but not limited to conduct which constitutes unauthorised access, interference and/or activities which may cause damage to the operation of a computer system or website (including the propagation of viruses, the use of malicious programs, and any attempts to overload computer systems). Any attempt to damage, undermine the legitimacy, security, maintenance, and operation of our Website may result in the enforcement of civil and/or criminal action or penalties. We reserve the right to seek damages as permitted by any applicable laws, regulations, and codes.</li>
                        <li className="index_item">You must not engage in any act that is inappropriate, unlawful, or prohibited by any law, regulation, or code, including but not limited to:<br/>
                            <ol className="index">
                                <li className="index_item">any act constituting breaches privacy (including submitting, posting, and/or uploading any private, confidential or personal information without lawful consent or authority);</li>
                                <li className="index_item">use our Website to defame our company, employees or related entities, or any third-party;</li>
                                <li className="index_item">the uploading and publishing of files and links that contain viruses or malicious content that may cause damage to our computer systems, or Website, Information Technology infrastructure or that of any other third-party; or</li>
                                <li className="index_item">posting or transmitting to our Website any unauthorised and unlawful material, including but not limited to material that is reasonably likely to cause annoyance, distress, harassment, harm; or which is defamatory, racist, bigoted, obscene, threatening, pornographic or otherwise; or which is detrimental to or in violation of our computer systems or a third party’s computer systems or network security.</li>
                            </ol>
                        </li>
                        <li className="index_item">We have the right to remove and take down, at our own discretion and without notice to you, any information that is submitted, posted or uploaded to our Website whether or not such information is ours, yours, or that of a third-party.</li>
                    </ol>
                    <h2 className="num-lvl-1"><b>Your Personal Information</b></h2>
                    <ol className="index">
                        <li>We shall collect, use, store, disclose and otherwise manage your personal information and if applicable, information regarding your state of affairs in accordance with our Privacy Policy. In order for you to engage and use our Tax Agent Services, you must authorise the collection, use, storage, disclosure and management of your personal information in accordance with our Privacy Policy.</li>
                        <li>We acknowledge that you retain the right in and to the personal information that you submit, post or upload via the use of our Website.</li>
                        <li>By submitting, posting, and/or uploading your personal information to our Website:<br/>
                            <ol className="index">
                                <li>you give us an irrevocable, perpetual, continuous, royalty-free and non-exclusive licence to collect, use, store, disclose and manage your personal information pursuant to our Privacy Policy;</li>
                                <li>you give us consent to use your personal information;</li>
                                <li>for direct marketing purposes as set out in our Privacy Policy. You may choose to unsubscribe from receiving such information or content at any time using the contact details below; and</li>
                                <li>you agree to the use and disclosure of your personal information for any other purposes as specified in our Privacy Policy.</li>
                            </ol>
                        </li>
                    </ol>
                    <h2 className="num-lvl-1"><b>Your Personal Information Security</b></h2>
                    <ol className="index">
                        <li>We shall take precautions and measures to protect personal information we hold from misuse, interference, and loss, as well as from unauthorised access, modification or disclosure.</li>
                        <li>If a feature is applicable to our Website from time to time, we may also give you the option of direct client access to our Website by way of log in ID and password so that you may:<br/>
                            <ol className="index">
                                <li>access your personal information; and/or</li>
                                <li>download documents from or upload documents to our Website.</li>
                            </ol>
                        </li>
                        <li>We do not make any warranties, guarantees or representations to you in respect of the security of your personal information when submitting, posting or uploading your personal information on our Website. You agree that if you submit, post and upload your personal information to our Website , you do so at your own discretion and risk. We shall not be held responsible or liable for any misuse, interference and loss, as well as from unauthorised access, modification or disclosure of your personal information.</li>
                    </ol>
                    <h2 className="num-lvl-1 bold">Our Online Applications &amp; Facilities</h2>
                    <p className="text">Access and use of any of our online applications and/or facilities contained on our Website enable us to store and retain any information submitted, posted, and/or uploaded, whether it constitutes personal information or otherwise.</p>
                    <h2 className="num-lvl-1">Internet Protocol (IP) Address</h2>
                    <ol className="index">
                        <li>We may collect personal information about you when you access and use our Website. While we do not use browsing information to identify you personally, we may record certain information about your access and use of our Website, such as which pages you visit, the time and date of your visit and the IP address assigned to your computer.</li>
                        <li>Your access and use of our Website is deemed to authorise our collection of personal information and/or content pertaining to your device ID, device type, tracking data, geo-location information, computer and connection information, statistics on page views, traffic to and from the sites, ad data, IP address (which is usually used to help diagnose problems with our servers and to administer our Website, and to help identify and gather demographic information about you) and standard web log information.</li>
                    </ol>
                    <h2 className="num-lvl-1">Cookies</h2>
                    <ol className="index">
                        <li>We also collect personal information through software such as ‘cookies’. A cookie is a text-only string of information that a website transfers to the cookie file of the browser on the hard disk of a user’s computer so that the website can remember that user. Without cookies, websites and their servers have no memory.</li>
                        <li>We use or other similar tracking technologies on our Website that help us track your usage, and remember your preferences, enabling us to provide you with a more effective website and better user experience.</li>
                        <li>This may enable recognition across different websites, services, devices and/or browsing sessions. Cookies are used for the purposes of identifying your internet browser, advertising and tracking, and/or storing any information related to your user personalisation. We may also use cookies for the purposes of secure services (that is, an area where you are required to log on) on our Website.</li>
                        <li>You may choose to disable or reject cookies through your internet browser, however, our Website may not work as intended or you may be prevented from accessing certain services if you do so.</li>
                        <li>If your browser is configured to reject all cookies you will be unable to use secure services on our Website that require cookies in order to participate. You may still be able to use some of the information-only pages even if you do not accept cookies.</li>
                        <li>Cookies may also be used to enable us to collect data that may include personal information. We shall handle any personal information collected by cookies in the same manner that we handle all other personal information as described in our Privacy Policy.</li>
                    </ol>
                    <h2 className="num-lvl-1">Liability</h2>
                    <ol className="index">
                        <li>To the maximum extent permitted by law, including the Australian Consumer Law, in no event shall we be liable for any direct and indirect loss, damage or expense – irrespective of the manner in which it occurs – which may arise from, or in connection, or related to your access or use of our Website and/or the information or materials or content contained within it, or as a result of the inaccessibility of our Website and/or the fact that certain information or materials, or content contained on it are incorrect, incomplete or not up to date.</li>
                        <li>We shall not be held liable for any loss of profit, loss or corruption of data, special, exemplary, punitive, incidental, indirect or consequential loss or damage suffered or incurred by you arising in connection with the use or access of our Website, any Tax Agent Services which we provide to you, or in connection with any act or omission by us, whether negligent or otherwise.</li>
                    </ol>
                    <h2 className="num-lvl-1">Website Terms of Use relating to Tax Agent Services</h2>
                    <ol className="index">
                        <li>This clause 12 shall apply if you engage us for Tax Agent Services. If you engage us for the provision of Tax Agent Services and provide us with your personal information and information relating to your state of affairs, via our Website, email, SMS or telephone, by mail and/or in person, you agree to authorise us to deal with your personal information and any information relating to your state of affairs for the purpose of providing Tax Agent Services, and in so doing agree for us to act on your behalf as your taxation agent and access your taxation records from the Australian Taxation Office (“<strong>ATO</strong>”) Portal. This will allow us to confirm and verify information and to discharge our obligations under any applicable at law.</li>
                        <li>By engaging our Tax Agent Services, you authorise us to contact you via telephone, SMS, email, or by mail in respect of any taxation matters that relate to you. In the provision of our Tax Agent Services, we may request further personal information or information in relation to your state of affairs directly from you, or indirectly from other parties as specified in our Privacy Policy. This may occur in instances (but is not limited to) where the personal information that you have provided to us is considered to be reasonably insufficient for the purposes of carrying out our Tax Agent Services.</li>
                        <li>We may use your personal information for direct marketing purposes as described in our Privacy Policy. Registration on our Website shall automatically subscribe you to our newsletter and marketing activities. Should you wish to unsubscribe, you may do so using the contact details below.</li>
                        <li>You are responsible for providing accurate, reliable, up to date and complete personal information. Failure to do so may result in the inability for us to provide you with the Tax Agent Services you seek. We shall not be held liable or responsible for the failure to perform Tax Agent Services if the personal information that you have provided to us is in some manner deemed to be inaccurate, unreliable, out of date, incomplete, or otherwise.</li>
                        <li>You acknowledge and understand that we reserve the right to, and have sole discretion to refuse to provide you with our Tax Agent Services, whether or not we consider the personal information that you provide to us to be inaccurate, unreliable, out of date, incomplete, or incorrect.</li>
                        <li>You acknowledge and agree to the collection, use, handling, storage, disclosure and management of your personal information by us in accordance with our Privacy Policy including disclosure to third parties in Australia or overseas who are engaged by us to facilitate the provision of Tax Agent Services to you.</li>
                    </ol>
                    <h2 className="num-lvl-1">Obligations in relation to Tax Agent Services</h2>
                    <ol className="index">
                        <li>This clause 13 shall apply if you engage us for Tax Agent Services. We shall endeavour to ensure that your personal information is accurate, complete and up to date, and will take steps to correct your personal information if you request that we correct your personal information, or if your personal information appears to be inaccurate, out of date, incomplete, unreliable, irrelevant or misleading. If you wish to request for your personal information to be corrected, please contact us using the details provided below.</li>
                        <li>You must provide us with correct, accurate, reliable, complete and up to date personal information. Notwithstanding clause 13.1, in the event that the personal information that you provide to us is incomplete, inaccurate, unreliable or out of date, or you choose not to provide certain information about you, we may be unable to provide you with the Tax Agent Services that you are seeking.</li>
                        <li>For the purposes of clause 13.2, you understand that civil and criminal action or penalties may apply in the event that you provide us with unreliable, inaccurate, incomplete, out of date, false, or misleading information. You accept that we shall not be held responsible or liable to you in respect of inaccurate, out of date, incomplete, unreliable, irrelevant or misleading personal information.</li>
                        <li>By providing us with your financial information in the course of us providing you with Tax Agent Services, you warrant that you have the relevant and necessary receipts/records for the deductions/rebates claimed in your tax return(s). You understand that it is your duty to keep the evidence pertaining to income/deductions for a minimum of 5 years. The ATO may impose a penalty or prosecute you if you are unable to provide receipts/records, or if the tax return is deemed to be incorrect/misleading. You understand that to obtain the benefit of “safe harbour” protections, you must provide to us “all relevant taxation information” to enable us to provide accurate statements to the ATO.</li>
                        <li>For work related expenses, you understand that you need to have written evidence if your total work-related claims exceed $300.00. All income/deductions/rebates included in your tax return(s) are based on your specific instructions and confirmation that you satisfy the relevant taxation requirements. We are bound by your instructions and the information that you provide to us, it is solely your responsibility to ensure that the personal information, financial information, other information pertaining to your state of affairs, and instructions that you provide us in the provision of our Tax Agent Services is correct, accurate, reliable, complete, and up to date.</li>
                        <li>If you engage us for the provision of Tax Agent Services, you agree that you authorise us to lodge your income tax return(s) on your behalf.</li>
                        <li>You must provide us with all the relevant and necessary information in order to enable us to provide accurate statements to the ATO. You discharge and indemnify us, our agents, officeholders, and employees from any liability arising on account of any audit or other investigations in respect of any undeclared income or excess claims made on your tax return(s), or any false or misleading information provided to the ATO on your behalf.</li>
                        <li>In the event our fees are not paid upfront and such fees are to be deducted from your tax refund, you authorise that your tax refund to be transferred to our trust account. You understand that you will be paid your tax refund after we deduct our fees. Any surfeit from your tax refund will be deposited into your nominated bank account via electronic transfer or paid to you by cheque.</li>
                    </ol>
                    <h2 className="num-lvl-1">Procedure for 1-Hour Refunds (Taxation Services)</h2>
                    <ol className="index">
                        <li>You understand and acknowledge that we need to do additional work to process an on the spot refund. Such additional work includes, but is not limited to, verification of your income, tax debt position and GST position. These verifications are important as they provide us with confirmation of your entitlement to a tax refund. We may verify/assess any debt you may owe State and Federal Governments, including to Centrelink and any relevant government department regarding Child Support Payments. Variations in any of these factors may reduce the amount of your income tax refund (if any). You fully understand that despite all these verifications, your actual refund may be reduced as a result of undisclosed debts to the Australian Government. You understand that even after the assessments of your debt position, we cannot confirm, let alone guarantee, your debt position with respect to any Government agency. A government agency to whom you owe money may take part or all of your income tax refund in satisfaction of outstanding debts.</li>
                        <li>You understand and acknowledge that once the necessary verifications have been completed, we retain full discretion to decide on your eligibility for 1-Hour refund. We may decline to provide you with 1-Hour tax refund without providing you with a reason. Your eligibility for, and amount of, any 1-Hour refunds offered by us is determined on a case by case basis.</li>
                        <li>You understand and acknowledge that 1-Hour refund cannot exceed AUD$500. The balance of your taxation refund, after deducting our fees and the amount of any on the spot advance paid (if any) will be deposited in your nominated bank account by way of electronic funds transfer, or alternatively sent to you by cheque once the Australian Taxation Office deposits your tax refund into our trust account. Electronic Funds Transfer/cheque deposits in your account may take 2-3 business days to clear.</li>
                    </ol>
                    <h2 className="num-lvl-1">1-Hour Refunds: Your Obligations to Us (Taxation Services)</h2>
                    <ol className="index">
                        <li>You understand and acknowledge that any money received by you from us will be treated as an advance to you. This amount will be set off against your actual taxation refund to be paid by the Australian Taxation Office. You understand that once a taxation refund is issued by the Australian Taxation Office, you will receive the balance of your taxation return <strong>after</strong> subtraction of the amount of your 1-Hour taxation return refund <strong>plus</strong> our fees. If a government agency takes part of your tax refund in satisfaction of an outstanding debt, then your actual refund will be lesser by that amount.</li>
                        <li>You understand and acknowledge that If your actual taxation refund from the Australian Taxation Office is less than the amount required to repay your 1-Hour taxation refund <strong>and</strong> our fees, you will be required to pay all amounts outstanding to us within 14 days of receipt of the Australian Taxation Office’s assessment.</li>
                        <li>You understand and acknowledge that if you do not pay all outstanding amounts owed to us within 14 days of the Australian Taxation Office Assessment, a Letter of Demand may be issued to you. Following provision of this Letter of Demand and the elapsing of the period for payment, we may, at our sole discretion, refer this debt to an external debt collection agency or commence proceedings against you in the Holland Park Magistrates Court. If we commence proceedings against you, you may become liable for pre and post judgment interest, legal costs, legal disbursements and our own administration fee of $275 inclusive of GST.</li>
                    </ol>
                    <h2 className="num-lvl-1">Fees Structure (Taxation Services)</h2>
                    <ol className="index">
                        <li>You understand and acknowledge the following terms of our fee structure and agree that you are liable to us for these amounts if you engage our services.<br/>
                            <ol className="index">
                                <li>Preparation and Lodgement of your Tax return – this work consists of collecting information concerning your taxable income, deductions and offsets. We will collate information and supporting documents for all your declarable income sources (e.g. salary, business, rental, foreign income, interest, dividends). We also collate information and documents for your expenses. This work can take from 20 minutes to a few days depending on the size and complexity of the taxation return. Our fee structure for this work is not fixed and depends on time and effort involved in preparing and lodging your tax return. An estimate of our fees will be provided to you in the tax refund estimate after our initial interview. If you are not happy with our fees or refund estimate you are under no obligation to proceed and you will not be charged anything for the initial interview. However, if you do wish to proceed and we lodge your taxation return, then the fees as declared to you will be payable. An additional fee of $39 plus GST is payable in the event you wish to pay for our services out of your taxation return proceeds.</li>
                                <li>1-Hour refund fees – Fees for 1-Hour refunds will be determined on a case by case basis. By way of guidance, this fee is typically between $350 and $450 plus GST for each 1-Hour taxation return refund. However, <strong>we stress this fee can be higher or lower than the guidance we have provided.</strong> The factors which determine the amount of our fee include:<br/>
                                    <ol className="num-lvl-4">
                                        <li>the size of your 1-Hour refund;</li>
                                        <li>the risk associated with advancing funds to you; and</li>
                                        <li>the amount of additional work required to assess whether you meet the necessary criteria for such an advance.</li>
                                    </ol>
                                </li>
                            </ol>
                        </li>
                        <li>Fee from refund service – This service is available where taxpayer does not pay fees upfront. If you are eligible, we can deduct the fees from your refund and Balance refund can be paid to you once ATO releases your refund. There is additional cost of $39 plus GST for this service. You must allow an additional 1-2 working days to receive the payment once ATO releases the Tax refund in our tax Agent Trust Account.</li>
                        <li>Fees recovery – Once you engage us as tax agent, you accept our condition that any prior amount owing to us can be deducted from this year’s tax refund. This means that if you have used our services in the past and our invoice is still unpaid, then that unpaid invoice will also be deducted from ATO refund this year. This means that your current year refund will be reduced by the current year invoice (fees and 1-hour refund) and prior year unpaid invoice (fees and 1-hour refund). You accept that we have the right to claim unpaid invoice from last 10 years from your current year tax refund issued by ATO in our trust bank account. In case we receive tax refund for ATO in our trust account, but we did not render any service to you in this year, even then we have to right recover previous unpaid invoice from your tax refund, and you will be getting balance after previous invoices are paid.</li>
                    </ol>
                    <h2 className="num-lvl-1">Authorization</h2>
                    <ol className="index">
                        <li>If you engage us for the provision of our services, such as tax agent services, you expressly authorise us to:<br/>
                            <ol className="abc-style">
                                <li>act as your taxation agent and carry out tax agent services on your behalf;</li>
                                <li>prepare and lodge your tax return(s) via the Australian Taxation Office (“<strong>ATO</strong>”) Portal on your behalf;</li>
                                <li>access your taxation records from the ATO Portal;</li>
                                <li>lodge your tax return(s) as an amendment if the ATO rejects your tax return(s) on the ground that it is already lodged;</li>
                                <li>add you to our ATO Portal until this authority is revoked;</li>
                                <li>change your bank details on the ATO Portal as instructed by you in respect of your nominated bank account, to ensure you obtain your ATO tax refund in a timely manner.</li>
                                <li>check your information with the document issuer or official record holder via third party systems for the purpose of confirming your identity; and</li>
                                <li>transfer ATO refunds to the bank details provided in the authorisation. You assume full responsibility for the accuracy of the bank details you provided. My Tax Refund Today shall not be held liable in the event of inaccuracies or errors in the bank details provided in the authorisation by you.</li>
                            </ol>
                        </li>
                    </ol>
                    <p className="text">In the event that you wish to revoke any authority contained in clause 4, you must email us at <a href="mailto:info@mytaxrefundtoday.com.au">info@mytaxrefundtoday.com.au</a>.</p>
                    <h2 className="num-lvl-1">Authorisation to Lodge Income Tax Return (Taxation Services)</h2>
                    <ol className="index">
                        <li>You declare that You have received and read a copy of the Terms &amp; Conditions, Refund Calculation Sheet(s)/Tax Invoice and Privacy Policy. You acknowledge that your Refund Calculation sheet displays your estimated taxation refund, tax agent fees for lodging your tax return, any tax agent fees for 1-Hour taxation refunds” to be paid to you as an advance to be repaid by you once your refund is released by the Australian Taxation Office. You understand and accept these figures as being accurate.</li>
                        <li>You authorise your tax refund to be transferred to your tax agent’s trust account. You understand that You will be paid the balance of your taxation refund only after your taxation agent has deducted its fees and any 1-Hour taxation refund paid to you.</li>
                        <li>You have read, accept and agree to be bound by the above terms and conditions and You authorise Milestone accounting Pty Ltd trading as My Tax Refund Today (Registered Tax Agent no. 00000000) to prepare and lodge your Income Tax Return.</li>
                    </ol>                              
                </div>

            </div>

        </section>
    );
}

